from turtle import Turtle

joe = Turtle()

def dice1():
  joe.pendown()
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.penup()
  joe.goto(50, 50)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.hideturtle()
  
def dice2():
  joe.pendown()
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.penup()
  joe.goto(30, 50)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(60, 50)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.hideturtle()
  
def dice3():
  joe.pendown()
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.penup()
  joe.goto(30, 30)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(50, 50)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(70, 70)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.hideturtle()
  
def dice4():
  joe.pendown()
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.penup()
  joe.goto(20, 70)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(65, 70)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(22, 20)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(65, 20)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.hideturtle()
  
def dice5():
  joe.pendown()
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.penup()
  joe.goto(50, 50)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(20, 70)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(70, 70)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(22, 20)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(70, 20)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.hideturtle()
  
def dice6():
  joe.pendown()
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.left(90)
  joe.forward(100)
  joe.penup()
  joe.goto(20, 70)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(45, 70)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(70, 70)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(45, 20)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(22, 20)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.penup()
  joe.goto(70, 20)
  joe.pendown()
  joe.color("black")
  joe.dot(10)
  joe.hideturtle()
 
